language: haxe
os:
  - linux

sudo: false
dist: trusty

haxe:
  - "3.2.1"
  - development

install:
  - git clone https://github.com/commonmark/cmark
  - export GITDEPPATH=$PWD/cmark/build/src
  - pushd cmark && mkdir build && pushd build && cmake .. && make libcmark_static && popd && cp src/cmark.h build/src/ && popd

script:
  - pushd lib
  - make all
  - popd

after_success:
  - pushd lib
  - make install
  - make test
  - popd
